---

- name: "configuration play."
  vars:
    environment_config:
      ENVIRONMENT: production
      TYPEORM_CONNECTION: postgres
      TYPEORM_MIGRATIONS_DIR: ./src/migrations
      TYPEORM_MIGRATIONS: ./src/migrations/*.ts
      TYPEORM_ENTITIES: ./src/modules/domain/**/*.entity.ts
      TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
      TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
      TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
      TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
      TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"
  hosts: web
  user: ubuntu
  become: true
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      wait_for_connection:

    - name: "install python for Ansible."
      become: true
      apt:
        name: ["python3"]
        state: latest
        update_cache: yes

  roles:
    - weareinteractive.environment
    - configure-server