- name: Make backend directory
  become: yes
  file:
    path: /home/ubuntu/backend
    state: directory

- name: Deploy backend
  become: yes
  unarchive:
    src: /tmp/workspace/backend.tar.gz
    dest: /home/ubuntu/backend/

- name: Record Env 
  become: yes
  shell: |
    echo {{ lookup('env', 'TYPEORM_HOST') }} > env_result.txt
    echo {{ lookup('env', 'TYPEORM_ENTITIES') }} >> env_result.txt
    echo {{ lookup('env', 'TYPEORM_USERNAME') }} >> env_result.txt

- name: Start backend with pm2
  become: yes
  shell: |
    export ENVIRONMENT=production
    export TYPEORM_CONNECTION=postgres
    export TYPEORM_HOST="{{ lookup('env', 'TYPEORM_HOST') }}"
    export TYPEORM_PORT="{{ lookup('env', 'TYPEORM_PORT') }}"
    export TYPEORM_ENTITIES="{{ lookup('env', 'TYPEORM_ENTITIES') }}"
    export TYPEORM_USERNAME="{{ lookup('env', 'TYPEORM_USERNAME') }}"
    export TYPEORM_PASSWORD="{{ lookup('env', 'TYPEORM_PASSWORD') }}"
    export TYPEORM_DATABASE="{{ lookup('env', 'TYPEORM_DATABASE') }}"
    cd /home/ubuntu/backend
    /usr/local/bin/pm2 start --name "backend" npm -- start